include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    prefer_expression_function_bodies: false
    public_member_api_docs: false
    omit_local_variable_types: false
    unnecessary_this: false
    prefer_mixin: false
