name: AbdoCare
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_dialogflow: ^0.1.3

  #Firebase Stuffs
  firebase_core: ^0.7.0
  rflutter_alert: ^1.1.0
  cloud_firestore: ^0.16.0+1
  cloud_functions: ^0.9.0
  firebase_storage: "^7.0.0"
  firebase_auth: ^0.20.1
  #firebase_messaging Temp verison (They're fixing this may cause error on ios)
  #firebase_messaging: ^8.0.0-dev.14

  bubble: ^1.1.9+1
  intl: ^0.16.1
  charts_flutter: ^0.9.0
  get_it: ^5.0.3
  syncfusion_flutter_gauges: ^18.4.33
  image_picker: ^0.6.7+21
  step_progress_indicator: ^0.2.5+8
  expandable: ^4.1.4
  youtube_player_flutter: ^7.0.0+7
  flutter_dialogflow_v2: ^0.3.2

  #provider
  provider: ^4.3.3
  #To save local cache
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.4
  flutter_launcher_icons: ^0.8.1
  

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/abdocare_logo.png'
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/image.png
    - assets/abdo-bot-briv-9ed7278f51f5.json
    - assets/Hospital_logo.png
    - assets/STIN_logo.png
    - assets/icon/Feeding.png
    - assets/icon/Grooming.png
    - assets/icon/Transfer.png
    - assets/icon/Toilet.png
    - assets/icon/Mobility.png
    - assets/icon/Dressing.png
    - assets/icon/Stairs.png
    - assets/icon/Bathing.png
    - assets/icon/Bowels.png
    - assets/icon/Bladder.png
    - assets/Painform.png
    - assets/training/walk.png
    - assets/training/sit.png
    - assets/training/housework.png
    - assets/training/drive.png
    - assets/training/work.png
    - assets/training/hospital.png
    - assets/training/watchTV.png
    - assets/training/scenery.png 
    - assets/training/protein.png 
    - assets/training/milk.png 
    - assets/training/fruit.png 
    - assets/training/vegetable.png 
    - assets/training/medicine.png 
    - assets/training/protein2.png 
    - assets/training/sleep.png 
    - assets/training/water.png 
    - assets/nurse.png
    - assets/user.png
    - assets/nurse2.png

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt-Bold.ttf
        - asset: assets/fonts/Prompt-Light.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
 
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
