name: AbdoCare
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3

  #Firebase Stuffs
  firebase_core: ^1.4.0
  rflutter_alert: ^2.0.2
  cloud_firestore: ^2.4.0
  cloud_functions: ^3.0.0
  firebase_storage: ^10.0.1
  firebase_auth: ^3.0.1

  bubble: ^1.2.1
  intl: ^0.17.0
  charts_flutter: ^0.11.0
  get_it: ^7.2.0
  syncfusion_flutter_gauges: ^19.2.47
  image_picker: ^0.8.2
  step_progress_indicator: ^1.0.1
  expandable: ^5.0.1
  youtube_player_flutter: ^8.0.0
  dialog_flowtter: ^0.3.1

  #provider
  provider: ^5.0.0
  #To save local cache
  shared_preferences: ^2.0.6
  syncfusion_flutter_charts: ^19.2.47+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.2
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/abdocare_logo.png'

flutter:
  assets:
    - assets/image.png
    - assets/abdo-bot-briv-9ed7278f51f5.json
    - assets/Hospital_logo.png
    - assets/STIN_logo.png
    - assets/icon/Feeding.png
    - assets/icon/Grooming.png
    - assets/icon/Transfer.png
    - assets/icon/Toilet.png
    - assets/icon/Mobility.png
    - assets/icon/Dressing.png
    - assets/icon/Stairs.png
    - assets/icon/Bathing.png
    - assets/icon/Bowels.png
    - assets/icon/Bladder.png
    - assets/Painform.png
    - assets/training/walk.png
    - assets/training/sit.png
    - assets/training/housework.png
    - assets/training/drive.png
    - assets/training/work.png
    - assets/training/hospital.png
    - assets/training/watchTV.png
    - assets/training/scenery.png
    - assets/training/protein.png
    - assets/training/milk.png
    - assets/training/fruit.png
    - assets/training/vegetable.png
    - assets/training/medicine.png
    - assets/training/protein2.png
    - assets/training/sleep.png
    - assets/training/water.png
    - assets/nurse.png
    - assets/user.png
    - assets/nurse2.png
    - assets/abdocare_logo.png

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt-Bold.ttf
        - asset: assets/fonts/Prompt-Light.ttf

  uses-material-design: true
