enum TrainingTopic {
  respiratoryDay0,
  painDay01,
  drainDay01,
  respiratoryDay1,
  bloodclotDay1,
  nutritionDay1,
  painDay2,
  infectionDay2,
  drainDay2,
  pulmanaryDay2,
  digestiveDay2,
  behaveDay2,
  painHome,
  infectionHome,
  surgicalIncisionHome,
  dailyActivityHome,
  foodHome
}
